[inboundConfig]
host = "localhost"
port = 9090

[inboundConfig.message]
headerLength = 2
versionNameString = ""
mtiLength = 4

[isoLibraryConfig]
fieldDefFilePath = "/Users/rivindumadushan/CodeBases/PTJalinBallerina/iso8583_tcp_inbound/resources/jposdefv87.xml"
fieldNamesFilePath = "/Users/rivindumadushan/CodeBases/PTJalinBallerina/iso8583_tcp_inbound/resources/jpos.csv"

[backendServiceConfig]
host = "localhost"
port = 9001